//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderID
    {
        public int IDOrder { get; set; }
        public string Cost { get; set; }
        public string Name { get; set; }
        public string AddressShop { get; set; }
        public string AddressClient { get; set; }
        public string Quantity { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
    }
}
