//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsStoreEntities : DbContext
    {
        public static SportsStoreEntities _context;
        public SportsStoreEntities()
            : base("name=SportsStoreEntities")
        {
        }
        public static SportsStoreEntities GetContext()
        {
            if (_context == null)
                _context = new SportsStoreEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasketID> BasketID { get; set; }
        public virtual DbSet<ClothesAndShoes> ClothesAndShoes { get; set; }
        public virtual DbSet<ForChildrenID> ForChildrenID { get; set; }
        public virtual DbSet<OrderID> OrderID { get; set; }
        public virtual DbSet<SportsGoods> SportsGoods { get; set; }
        public virtual DbSet<UnderwearID> UnderwearID { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
